/**
 * 书目清单（281 部），对应 v2/book-title 的 data.rows。
 *
 * 在原始字段之外为每部书补了 `abbr`：按 toc 生成的 cs_para_map 风格缩写。
 * cs_para_map.ts 已有的名字直接复用，缺失的按同风格补齐。
 *
 * 用于 search 工具的 ref 字段：按命中的 path 首个书级节点回查本表得到缩写。
 * 原始数据里的 created_at / updated_at 为逐行相同的落库时间戳，已省略。
 */

export interface BookRow {
  id: number;
  book: number;
  paragraph: number;
  title: string;
  sn: number;
  toc: string;
  tags: string[];
  related_name: string | null;
  abbr: string;
}

export const BOOK_ROWS: BookRow[] = [
  { id: 1678, book: 1, paragraph: 2, title: "namakkārapāḷi", sn: 1, toc: "Namakkārapāḷi", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "namakkāra", "namakkārapāḷi"], related_name: "NK", abbr: "namakkāra." },
  { id: 1679, book: 1, paragraph: 159, title: "namakkāraṭīkā", sn: 2, toc: "Namakkāraṭīkā", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "namakkāra", "namakkāraṭīkā", "ṭīkā"], related_name: "NK", abbr: "namakkāra.ṭī." },
  { id: 1680, book: 2, paragraph: 2, title: "mahāpaṇāmapāṭha", sn: 3, toc: "Mahāpaṇāmapāṭha", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "mahāpaṇāmapāṭha"], related_name: null, abbr: "mahāpaṇāma." },
  { id: 1681, book: 2, paragraph: 428, title: "tigumbacetiya thomanā", sn: 4, toc: "Tigumbacetiya thomanā", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "mahāpaṇāmapāṭha"], related_name: null, abbr: "tigumba." },
  { id: 1682, book: 2, paragraph: 479, title: "vāsamālinīkya", sn: 5, toc: "Vāsamālinīkya", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "mahāpaṇāmapāṭha"], related_name: null, abbr: "vāsamālinī." },
  { id: 1683, book: 3, paragraph: 2, title: "lakkhaṇāto", sn: 6, toc: "Lakkhaṇāto", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "lakkhaṇāto"], related_name: null, abbr: "lakkhaṇā." },
  { id: 1684, book: 4, paragraph: 2, title: "suttavandanā", sn: 7, toc: "Suttavandanā", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "suttavandanā"], related_name: null, abbr: "suttavandanā." },
  { id: 1685, book: 5, paragraph: 2, title: "jinālaṅkāra", sn: 8, toc: "Jinālaṅkāra", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "jinālaṅkāra"], related_name: null, abbr: "jinālaṅkāra." },
  { id: 1686, book: 6, paragraph: 2, title: "kamalāñjali", sn: 9, toc: "Kamalāñjali", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "kamalāñjali"], related_name: null, abbr: "kamalāñjali." },
  { id: 1687, book: 7, paragraph: 2, title: "pajjamadhu", sn: 10, toc: "Pajjamadhu", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "pajjamadhu"], related_name: null, abbr: "pajjamadhu." },
  { id: 1688, book: 8, paragraph: 2, title: "buddhaguṇagāthāvalī", sn: 11, toc: "Buddhaguṇagāthāvalī", tags: ["añña", "buddha-vandanā ganthasaṅgaha", "buddhaguṇagāthāvalī"], related_name: null, abbr: "buddhaguṇagāthāvalī." },
  { id: 1689, book: 9, paragraph: 2, title: "abhidhānappadīpikāṭīkā", sn: 12, toc: "Abhidhānappadīpikāṭīkā", tags: ["abhidhānappadīpikā", "abhidhānappadīpikāṭīkā", "añña", "byākaraṇa ganthasaṅgaha", "nirutti"], related_name: "dict", abbr: "abhidhāna.ṭī." },
  { id: 1690, book: 10, paragraph: 2, title: "subodhālaṅkāro", sn: 13, toc: "Subodhālaṅkāro", tags: ["añña", "byākaraṇa ganthasaṅgaha", "nirutti", "subodhālaṅkāra"], related_name: "subo", abbr: "subodhālaṅkāra." },
  { id: 1691, book: 11, paragraph: 2, title: "subodhālaṅkāraṭīkā", sn: 14, toc: "Subodhālaṅkāraṭīkā", tags: ["añña", "byākaraṇa ganthasaṅgaha", "nirutti", "subodhālaṅkāra", "subodhālaṅkāraṭīkā"], related_name: "subo", abbr: "subodhālaṅkāra.ṭī." },
  { id: 1692, book: 12, paragraph: 2, title: "bālāvatāra", sn: 15, toc: "Bālāvatāra", tags: ["avatāra", "añña", "byākaraṇa ganthasaṅgaha", "bālāvatāra", "nirutti"], related_name: null, abbr: "bālāvatāra." },
  { id: 1693, book: 13, paragraph: 2, title: "moggallānasuttapāṭho", sn: 16, toc: "Moggallānasuttapāṭho", tags: ["añña", "byākaraṇa ganthasaṅgaha", "moggallānasuttapāṭha", "nirutti"], related_name: null, abbr: "moggallāna.sutta." },
  { id: 1694, book: 13, paragraph: 1105, title: "moggallānabyākaraṇaṃ", sn: 17, toc: "Moggallānabyākaraṇaṃ", tags: ["añña", "byākaraṇa ganthasaṅgaha", "moggallānabyākaraṇa", "nirutti"], related_name: null, abbr: "moggallāna.byākaraṇa." },
  { id: 1695, book: 14, paragraph: 2, title: "kaccāyanabyākaraṇaṃ", sn: 18, toc: "Kaccāyanabyākaraṇaṃ", tags: ["añña", "byākaraṇa ganthasaṅgaha", "kaccāyanabyākaraṇa", "nirutti"], related_name: null, abbr: "kaccāyana.byākaraṇa." },
  { id: 1696, book: 14, paragraph: 715, title: "mahākaccāyanasaddāpāṭha", sn: 19, toc: "Mahākaccāyanasaddāpāṭha", tags: ["añña", "byākaraṇa ganthasaṅgaha", "kaccāyanabyākaraṇa", "nirutti"], related_name: null, abbr: "mahākaccāyana.sadda." },
  { id: 1697, book: 15, paragraph: 2, title: "saddanītippakaraṇaṃ (padamālā)", sn: 20, toc: "Saddanītippakaraṇaṃ (padamālā)", tags: ["añña", "byākaraṇa ganthasaṅgaha", "nirutti", "padamālā", "saddanītippakaraṇa"], related_name: null, abbr: "saddanīti.pada." },
  { id: 1698, book: 16, paragraph: 2, title: "saddanītippakaraṇaṃ (dhātumālā)", sn: 21, toc: "Saddanītippakaraṇaṃ (dhātumālā)", tags: ["añña", "byākaraṇa ganthasaṅgaha", "dhātumālā", "nirutti", "saddanītippakaraṇa"], related_name: null, abbr: "saddanīti.dhātu." },
  { id: 1699, book: 17, paragraph: 2, title: "padarūpasiddhi", sn: 22, toc: "Padarūpasiddhi", tags: ["añña", "byākaraṇa ganthasaṅgaha", "nirutti", "padarūpasiddhi"], related_name: null, abbr: "padarūpasiddhi." },
  { id: 1700, book: 18, paragraph: 2, title: "moggallāna-pañcikā-ṭīkā", sn: 23, toc: "Moggallāna pañcikā ṭīkā", tags: ["añña", "byākaraṇa ganthasaṅgaha", "moggallāna pañcikā ṭīkā", "nirutti"], related_name: null, abbr: "moggallāna.pañcikā.ṭī." },
  { id: 1701, book: 19, paragraph: 2, title: "payogasiddhipāḷi", sn: 24, toc: "Payogasiddhipāḷi", tags: ["añña", "byākaraṇa ganthasaṅgaha", "nirutti", "payogasiddhipāḷi"], related_name: null, abbr: "payogasiddhi." },
  { id: 1702, book: 20, paragraph: 2, title: "vuttodayaṃ", sn: 25, toc: "Vuttodayaṃ", tags: ["añña", "byākaraṇa ganthasaṅgaha", "nirutti", "vuttodaya"], related_name: null, abbr: "vuttodaya." },
  { id: 1703, book: 21, paragraph: 2, title: "abhidhānappadīpikā", sn: 26, toc: "Abhidhānappadīpikā", tags: ["abhidhānappadīpikā", "añña", "byākaraṇa ganthasaṅgaha", "nirutti"], related_name: "dict", abbr: "abhidhāna." },
  { id: 1704, book: 22, paragraph: 2, title: "niruttidīpanīpāṭha", sn: 27, toc: "Niruttidīpanīpāṭha", tags: ["añña", "leḍī sayādo", "nirutti", "niruttidīpanīpāṭha"], related_name: null, abbr: "niruttidīpanī." },
  { id: 1705, book: 23, paragraph: 2, title: "paramatthadīpanī", sn: 28, toc: "Paramatthadīpanī", tags: ["abhidhamma", "abhidhammatthasaṅgaha", "añña", "leḍī sayādo", "paramatthadīpanī"], related_name: "abhi9", abbr: "paramatthadīpanī." },
  { id: 1706, book: 24, paragraph: 2, title: "anudīpanīpāṭha", sn: 29, toc: "Anudīpanīpāṭha", tags: ["abhidhamma", "abhidhammatthasaṅgaha", "anudīpanīpāṭha", "añña", "leḍī sayādo"], related_name: "abhi9", abbr: "anudīpanī." },
  { id: 1707, book: 25, paragraph: 2, title: "paṭṭhānuddesa dīpanīpāṭha", sn: 30, toc: "Paṭṭhānuddesa dīpanīpāṭha", tags: ["abhidhamma", "añña", "leḍī sayādo", "paṭṭhāna", "paṭṭhānuddesa dīpanīpāṭha"], related_name: null, abbr: "paṭṭhānuddesadīpanī." },
  { id: 1708, book: 26, paragraph: 2, title: "caturārakkhadīpanī", sn: 31, toc: "Caturārakkhadīpanī", tags: ["añña", "caturārakkhadīpanī", "dīpanī", "nīti-ganthasaṅgaha"], related_name: null, abbr: "caturārakkhadīpanī." },
  { id: 1709, book: 27, paragraph: 2, title: "kavidappaṇanīti", sn: 32, toc: "Kavidappaṇanīti", tags: ["añña", "kavidappaṇanīti", "nīti-ganthasaṅgaha"], related_name: null, abbr: "kavidappaṇanīti." },
  { id: 1710, book: 28, paragraph: 2, title: "nītimañjarī", sn: 33, toc: "Nītimañjarī", tags: ["añña", "nīti-ganthasaṅgaha", "nītimañjarī"], related_name: null, abbr: "nītimañjarī." },
  { id: 1711, book: 29, paragraph: 2, title: "dhammanīti", sn: 34, toc: "Dhammanīti", tags: ["añña", "dhammanīti", "nīti-ganthasaṅgaha"], related_name: null, abbr: "dhammanīti." },
  { id: 1712, book: 30, paragraph: 2, title: "mahārahanīti", sn: 35, toc: "Mahārahanīti", tags: ["añña", "mahārahanīti", "nīti-ganthasaṅgaha"], related_name: null, abbr: "mahārahanīti." },
  { id: 1713, book: 31, paragraph: 2, title: "lokanīti", sn: 36, toc: "Lokanīti", tags: ["añña", "lokanīti", "nīti-ganthasaṅgaha"], related_name: null, abbr: "lokanīti." },
  { id: 1714, book: 32, paragraph: 2, title: "suttantanīti", sn: 37, toc: "Suttantanīti", tags: ["añña", "nīti-ganthasaṅgaha", "suttantanīti"], related_name: null, abbr: "suttantanīti." },
  { id: 1715, book: 32, paragraph: 134, title: "vasalasutta", sn: 38, toc: "Vasalasutta", tags: ["añña", "nīti-ganthasaṅgaha", "suttantanīti"], related_name: null, abbr: "vasalasutta." },
  { id: 1716, book: 33, paragraph: 2, title: "sūrassatīnīti", sn: 39, toc: "Sūrassatīnīti", tags: ["añña", "nīti-ganthasaṅgaha", "sūrassatīnīti"], related_name: null, abbr: "sūrassatīnīti." },
  { id: 1717, book: 34, paragraph: 2, title: "cāṇakyanītipāḷi", sn: 40, toc: "Cāṇakyanītipāḷi", tags: ["añña", "cāṇakyanītipāḷi", "nīti-ganthasaṅgaha"], related_name: null, abbr: "cāṇakyanīti." },
  { id: 1718, book: 35, paragraph: 2, title: "naradakkhadīpanī", sn: 41, toc: "Naradakkhadīpanī", tags: ["añña", "naradakkhadīpanī", "nīti-ganthasaṅgaha"], related_name: null, abbr: "naradakkhadīpanī." },
  { id: 1719, book: 36, paragraph: 2, title: "rasavāhinī", sn: 42, toc: "Rasavāhinī", tags: ["añña", "pakiṇṇaka-ganthasaṅgaha", "rasavāhinī"], related_name: null, abbr: "rasavāhinī." },
  { id: 1720, book: 37, paragraph: 2, title: "sīmavisodhanī", sn: 43, toc: "Sīmavisodhanī", tags: ["añña", "pakiṇṇaka", "pakiṇṇaka-ganthasaṅgaha", "sīmavisodhanī"], related_name: null, abbr: "sīmavisodhanī." },
  { id: 1721, book: 38, paragraph: 2, title: "vessantarāgīti", sn: 44, toc: "Vessantarāgīti", tags: ["añña", "pakiṇṇaka-ganthasaṅgaha", "vessantarāgīti"], related_name: null, abbr: "vessantarāgīti." },
  { id: 1722, book: 39, paragraph: 3, title: "(saṅgayana-puccha vissajjanā) dīghanikāye", sn: 45, toc: "(saṅgayana-puccha vissajjanā) Dīghanikāye", tags: ["añña", "dīghanikāya", "saṅgayana-puccha vissajjanā", "sutta"], related_name: null, abbr: "saṅgāyana.dī." },
  { id: 1723, book: 40, paragraph: 3, title: "(saṅgayana-puccha vissajjanā) majjhimanikāya", sn: 46, toc: "(saṅgayana-puccha vissajjanā) Majjhimanikāya", tags: ["añña", "majjhimanikāya", "saṅgayana-puccha vissajjanā", "sutta"], related_name: null, abbr: "saṅgāyana.ma." },
  { id: 1724, book: 41, paragraph: 3, title: "(saṅgayana-puccha vissajjanā) saṃyuttanikāye", sn: 47, toc: "(saṅgayana-puccha vissajjanā) Saṃyuttanikāye", tags: ["añña", "saṃyuttanikāya", "saṅgayana-puccha vissajjanā", "sutta"], related_name: null, abbr: "saṅgāyana.saṃ." },
  { id: 1725, book: 42, paragraph: 3, title: "(saṅgayana-puccha vissajjanā) aṅguttaranikāye", sn: 48, toc: "(saṅgayana-puccha vissajjanā) Aṅguttaranikāye", tags: ["añña", "aṅguttaranikāya", "saṅgayana-puccha vissajjanā", "sutta"], related_name: null, abbr: "saṅgāyana.a." },
  { id: 1726, book: 43, paragraph: 2, title: "(saṅgayana-puccha vissajjanā) vinayapiṭaka", sn: 49, toc: "(saṅgayana-puccha vissajjanā) Vinayapiṭaka", tags: ["añña", "saṅgayana-puccha vissajjanā", "vinaya", "vinayapiṭaka"], related_name: null, abbr: "saṅgāyana.vinaya." },
  { id: 1727, book: 44, paragraph: 2, title: "(saṅgayana-puccha vissajjanā) abhidhammapiṭaka", sn: 50, toc: "(saṅgayana-puccha vissajjanā) Abhidhammapiṭaka", tags: ["abhidhamma", "abhidhammapiṭaka", "añña", "saṅgayana-puccha vissajjanā"], related_name: null, abbr: "saṅgāyana.abhidhamma." },
  { id: 1728, book: 45, paragraph: 2, title: "(saṅgayana-puccha vissajjanā) aṭṭhakathā", sn: 51, toc: "(saṅgayana-puccha vissajjanā) Aṭṭhakathā", tags: ["añña", "aṭṭhakathā", "saṅgayana-puccha vissajjanā"], related_name: null, abbr: "saṅgāyana.aṭṭhakathā." },
  { id: 1729, book: 46, paragraph: 1, title: "milidaṭīkā", sn: 52, toc: "Milidaṭīkā", tags: ["añña", "khuddakanikāya", "milidaṭīkā", "milindapañha", "sihaḷa-ganthasaṅgaha", "sutta", "ṭīkā"], related_name: "kn18", abbr: "milinda.ṭī." },
  { id: 1730, book: 47, paragraph: 1, title: "padamañjarī", sn: 53, toc: "Padamañjarī ", tags: ["añña", "nirutti", "padamañjarī", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "padamañjarī." },
  { id: 1731, book: 48, paragraph: 1, title: "padasādhanaṃ", sn: 54, toc: "Padasādhanaṃ ", tags: ["añña", "nirutti", "padasādhana", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "padasādhana." },
  { id: 1732, book: 49, paragraph: 1, title: "saddabindu pakaraṇaṃ", sn: 55, toc: "Saddabindu pakaraṇaṃ", tags: ["añña", "nirutti", "saddabindupakaraṇa", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "saddabindu." },
  { id: 1733, book: 50, paragraph: 1, title: "kaccāyana  dhātu mañjūsā", sn: 56, toc: "Kaccāyana  dhātu mañjūsā", tags: ["añña", "kaccāyana", "kaccāyanadhātumañjūsā", "nirutti", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "kaccāyana.dhātumañjūsā." },
  { id: 1734, book: 51, paragraph: 1, title: "samantakūṭavaṇṇanā", sn: 57, toc: "Samantakūṭavaṇṇanā ", tags: ["añña", "samantakūṭavaṇṇanā", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "samantakūṭavaṇṇanā." },
  { id: 1735, book: 52, paragraph: 1, title: "moggallāna vuttivivaraṇapañcikā.", sn: 58, toc: "Moggallāna vuttivivaraṇapañcikā. ", tags: ["añña", "moggallāna vuttivivaraṇapañcikā", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "moggallāna.vuttivivaraṇapañcikā." },
  { id: 1736, book: 53, paragraph: 1, title: "thupavaṃsa", sn: 59, toc: "Thupavaṃso ", tags: ["añña", "sihaḷa-ganthasaṅgaha", "thupavaṃsa"], related_name: null, abbr: "thupavaṃsa." },
  { id: 1737, book: 54, paragraph: 1, title: "dāṭhāvaṃsa", sn: 60, toc: "Dāṭhāvaṃso ", tags: ["añña", "dāṭhāvaṃsa", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "dāṭhāvaṃsa." },
  { id: 1738, book: 55, paragraph: 1, title: "dhātupāṭha  vilāsiniyā", sn: 61, toc: "Dhātupāṭha  vilāsiniyā", tags: ["añña", "dhātupāṭha vilāsiniyā", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "dhātupāṭha.vilāsinī." },
  { id: 1739, book: 56, paragraph: 1, title: "dhātuvaṃsa", sn: 62, toc: "Dhātuvaṃso ", tags: ["añña", "dhātuvaṃsa", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "dhātuvaṃsa." },
  { id: 1740, book: 57, paragraph: 1, title: "hatthavanagallavihāra  vaṃso", sn: 63, toc: "Hatthavanagallavihāra  vaṃso", tags: ["añña", "hatthavanagallavihāravaṃsa", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "hatthavanagallavihāravaṃsa." },
  { id: 1741, book: 58, paragraph: 1, title: "jinacaritaya", sn: 64, toc: "Jinacaritaya ", tags: ["añña", "jinacaritaya", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "jinacarita." },
  { id: 1742, book: 59, paragraph: 1, title: "jinavaṃsadīpaṃ", sn: 65, toc: "Jinavaṃsadīpaṃ ", tags: ["añña", "jinavaṃsadīpa", "sihaḷa-ganthasaṅgaha"], related_name: null, abbr: "jinavaṃsadīpa." },
  { id: 1743, book: 60, paragraph: 1, title: "telakaṭāhagāthā", sn: 66, toc: "Telakaṭāhagāthā ", tags: ["añña", "sihaḷa-ganthasaṅgaha", "telakaṭāhagāthā"], related_name: null, abbr: "telakaṭāhagāthā." },
  { id: 1744, book: 61, paragraph: 2, title: "cūḷaganthavaṃsapāḷi", sn: 67, toc: "Cūḷaganthavaṃsapāḷi", tags: ["añña", "cūḷaganthavaṃsapāḷi", "vaṃsa ganthasaṅgaha", "vaṃsa-ganthasaṅgaha"], related_name: null, abbr: "cūḷaganthavaṃsa." },
  { id: 1745, book: 62, paragraph: 2, title: "sāsanavaṃsappadīpikā", sn: 68, toc: "Sāsanavaṃsappadīpikā", tags: ["añña", "sāsanavaṃsappadīpikā", "vaṃsa ganthasaṅgaha", "vaṃsa-ganthasaṅgaha"], related_name: null, abbr: "sāsanavaṃsappadīpikā." },
  { id: 1746, book: 63, paragraph: 2, title: "mahāvaṃsapāḷi", sn: 69, toc: "Mahāvaṃsapāḷi", tags: ["añña", "mahāvaṃsapāḷi", "vaṃsa ganthasaṅgaha", "vaṃsa-ganthasaṅgaha"], related_name: null, abbr: "mahāvaṃsa." },
  { id: 1747, book: 64, paragraph: 2, title: "visuddhimagga", sn: 70, toc: "Visuddhimaggo(Paṭhamo bhāgo)", tags: ["añña", "aṭṭhakathā", "paṭhamo bhāgo", "visuddhimagga"], related_name: "vism", abbr: "visuddhi.1." },
  { id: 1748, book: 65, paragraph: 2, title: "visuddhimagga", sn: 71, toc: "Visuddhimaggo(Dutiyo bhāgo)", tags: ["añña", "aṭṭhakathā", "dutiyo bhāgo", "visuddhimagga"], related_name: "vism", abbr: "visuddhi.2." },
  { id: 1749, book: 66, paragraph: 2, title: "visuddhimagga-mahāṭīkā", sn: 72, toc: "Visuddhimagga-mahāṭīkā(Paṭhamo bhāgo)", tags: ["añña", "mahāṭīkā", "paṭhamo bhāgo", "visuddhimagga", "ṭīkā"], related_name: "vism", abbr: "visuddhi.mahāṭī.1." },
  { id: 1750, book: 67, paragraph: 2, title: "visuddhimagga-mahāṭīkā", sn: 73, toc: "Visuddhimagga-mahāṭīkā(Dutiyo bhāgo)", tags: ["añña", "dutiyo bhāgo", "mahāṭīkā", "visuddhimagga", "ṭīkā"], related_name: "vism", abbr: "visuddhi.mahāṭī.2." },
  { id: 1751, book: 68, paragraph: 2, title: "visuddhimagga nidānakathā", sn: 74, toc: "Visuddhimagga nidānakathā", tags: ["añña", "nidānakathā", "visuddhimagga", "ṭīkā"], related_name: null, abbr: "visuddhi.nidāna." },
  { id: 1752, book: 69, paragraph: 3, title: "paṭṭhānapāḷi", sn: 75, toc: "Paṭṭhānapāḷi(Dutiyo bhāgo)", tags: ["abhidhamma", "mūla", "paṭṭhāna", "paṭṭhānapāḷi", "pāḷi"], related_name: "abhi7", abbr: "paṭṭhāna.2." },
  { id: 1753, book: 70, paragraph: 3, title: "paṭṭhānapāḷi", sn: 76, toc: "Paṭṭhānapāḷi(Tatiyo bhāgo)", tags: ["abhidhamma", "mūla", "paṭṭhāna", "paṭṭhānapāḷi", "pāḷi"], related_name: "abhi7", abbr: "paṭṭhāna.3." },
  { id: 1754, book: 71, paragraph: 3, title: "paṭṭhānapāḷi", sn: 77, toc: "Paṭṭhānapāḷi(Catuttho bhāgo)", tags: ["abhidhamma", "mūla", "paṭṭhāna", "paṭṭhānapāḷi", "pāḷi"], related_name: "abhi7", abbr: "paṭṭhāna.4." },
  { id: 1755, book: 72, paragraph: 3, title: "paṭṭhānapāḷi", sn: 78, toc: "Paṭṭhānapāḷi(Pañcamo bhāgo)", tags: ["abhidhamma", "mūla", "paṭṭhāna", "paṭṭhānapāḷi", "pāḷi"], related_name: "abhi7", abbr: "paṭṭhāna.5." },
  { id: 1756, book: 73, paragraph: 3, title: "dhammasaṅgaṇīpāḷi", sn: 79, toc: "Dhammasaṅgaṇīpāḷi", tags: ["abhidhamma", "dhammasaṅgaṇī", "mūla", "pāḷi"], related_name: "abhi1", abbr: "dha.sa." },
  { id: 1757, book: 74, paragraph: 3, title: "vibhaṅgapāḷi", sn: 80, toc: "Vibhaṅgapāḷi", tags: ["abhidhamma", "mūla", "pāḷi", "vibhaṅga"], related_name: "abhi2", abbr: "vibha." },
  { id: 1758, book: 75, paragraph: 3, title: "dhātukathāpāḷi", sn: 81, toc: "Dhātukathāpāḷi", tags: ["abhidhamma", "dhātukathā", "mūla", "pāḷi"], related_name: "abhi3", abbr: "dhātu.kathā." },
  { id: 1759, book: 76, paragraph: 3, title: "puggalapaññattipāḷi", sn: 82, toc: "Puggalapaññattipāḷi", tags: ["abhidhamma", "mūla", "puggalapaññatti", "pāḷi"], related_name: "abhi4", abbr: "puggala.paññatti." },
  { id: 1760, book: 77, paragraph: 3, title: "kathāvatthupāḷi", sn: 83, toc: "Kathāvatthupāḷi", tags: ["abhidhamma", "kathāvatthu", "mūla", "pāḷi"], related_name: "abhi5", abbr: "kathā.vatthu." },
  { id: 1761, book: 78, paragraph: 3, title: "yamakapāḷi", sn: 84, toc: "Yamakapāḷi (paṭhamo bhāgo)", tags: ["abhidhamma", "mūla", "pāḷi", "yamaka", "yamakapāḷi"], related_name: "abhi6", abbr: "yama.1." },
  { id: 1762, book: 79, paragraph: 3, title: "yamakapāḷi", sn: 85, toc: "Yamakapāḷi (dutiyo bhāgo)", tags: ["abhidhamma", "mūla", "pāḷi", "yamaka", "yamakapāḷi"], related_name: "abhi6", abbr: "yama.2." },
  { id: 1763, book: 80, paragraph: 3, title: "yamakapāḷi", sn: 86, toc: "Yamakapāḷi (tatiyo bhāgo)", tags: ["abhidhamma", "mūla", "pāḷi", "yamaka", "yamakapāḷi"], related_name: "abhi6", abbr: "yama.3." },
  { id: 1764, book: 81, paragraph: 3, title: "paṭṭhānapāḷi", sn: 87, toc: "Paṭṭhānapāḷi(Paṭhamo bhāgo)", tags: ["abhidhamma", "mūla", "paṭṭhāna", "paṭṭhānapāḷi", "pāḷi"], related_name: "abhi7", abbr: "paṭṭhāna.1." },
  { id: 1765, book: 82, paragraph: 3, title: "dasakanipātapāḷi", sn: 88, toc: "Dasakanipātapāḷi", tags: ["aṅguttaranikāya", "dasakanipāta", "mūla", "nipāta", "pāḷi", "sutta"], related_name: "an10", abbr: "a.ni.10." },
  { id: 1766, book: 83, paragraph: 3, title: "ekādasakanipātapāḷi", sn: 89, toc: "Ekādasakanipātapāḷi", tags: ["aṅguttaranikāya", "ekādasakanipāta", "mūla", "nipāta", "pāḷi", "sutta"], related_name: "an11", abbr: "a.ni.11." },
  { id: 1767, book: 84, paragraph: 3, title: "ekakanipātapāḷi", sn: 90, toc: "Ekakanipātapāḷi", tags: ["aṅguttaranikāya", "ekakanipāta", "mūla", "nipāta", "pāḷi", "sutta"], related_name: "an1", abbr: "a.ni.1." },
  { id: 1768, book: 85, paragraph: 3, title: "dukanipātapāḷi", sn: 91, toc: "Dukanipātapāḷi", tags: ["aṅguttaranikāya", "dukanipāta", "mūla", "nipāta", "pāḷi", "sutta"], related_name: "an2", abbr: "a.ni.2." },
  { id: 1769, book: 86, paragraph: 3, title: "tikanipātapāḷi", sn: 92, toc: "Tikanipātapāḷi", tags: ["aṅguttaranikāya", "mūla", "nipāta", "pāḷi", "sutta", "tikanipāta"], related_name: "an3", abbr: "a.ni.3." },
  { id: 1770, book: 87, paragraph: 3, title: "catukkanipātapāḷi", sn: 93, toc: "Catukkanipātapāḷi", tags: ["aṅguttaranikāya", "catukkanipāta", "mūla", "nipāta", "pāḷi", "sutta"], related_name: "an4", abbr: "a.ni.4." },
  { id: 1771, book: 88, paragraph: 3, title: "pañcakanipātapāḷi", sn: 94, toc: "Pañcakanipātapāḷi", tags: ["aṅguttaranikāya", "mūla", "nipāta", "pañcakanipāta", "pāḷi", "sutta"], related_name: "an5", abbr: "a.ni.5." },
  { id: 1772, book: 89, paragraph: 3, title: "chakkanipātapāḷi", sn: 95, toc: "Chakkanipātapāḷi", tags: ["aṅguttaranikāya", "chakkanipāta", "mūla", "nipāta", "pāḷi", "sutta"], related_name: "an6", abbr: "a.ni.6." },
  { id: 1773, book: 90, paragraph: 3, title: "sattakanipātapāḷi", sn: 96, toc: "Sattakanipātapāḷi", tags: ["aṅguttaranikāya", "mūla", "nipāta", "pāḷi", "sattakanipāta", "sutta"], related_name: "an7", abbr: "a.ni.7." },
  { id: 1774, book: 91, paragraph: 3, title: "aṭṭhakanipātapāḷi", sn: 97, toc: "Aṭṭhakanipātapāḷi", tags: ["aṅguttaranikāya", "aṭṭhakanipāta", "mūla", "nipāta", "pāḷi", "sutta"], related_name: "an8", abbr: "a.ni.8." },
  { id: 1775, book: 92, paragraph: 3, title: "navakanipātapāḷi", sn: 98, toc: "Navakanipātapāḷi", tags: ["aṅguttaranikāya", "mūla", "navakanipāta", "nipāta", "pāḷi", "sutta"], related_name: "an9", abbr: "a.ni.9." },
  { id: 1776, book: 93, paragraph: 3, title: "dīghanikāyapāḷi", sn: 99, toc: "(DN) Sīlakkhandhavaggapāḷi", tags: ["dīghanikāya", "mūla", "pāḷi", "sutta", "sīlakkhandhavagga"], related_name: "dn1", abbr: "dī.ni.1." },
  { id: 1777, book: 94, paragraph: 3, title: "dīghanikāyapāḷi", sn: 100, toc: "(DN) Mahāvaggapāḷi", tags: ["dīghanikāya", "mahāvagga", "mūla", "pāḷi", "sutta"], related_name: "dn2", abbr: "dī.ni.2." },
  { id: 1778, book: 95, paragraph: 3, title: "dīghanikāyapāḷi", sn: 101, toc: "(DN) Pāthikavaggapāḷi", tags: ["dīghanikāya", "mūla", "pāthikavagga", "pāḷi", "sutta"], related_name: "dn3", abbr: "dī.ni.3." },
  { id: 1779, book: 96, paragraph: 4, title: "dhammasaṅgaṇī-aṭṭhakathā", sn: 102, toc: "Dhammasaṅgaṇī-aṭṭhakathā", tags: ["abhidhamma", "aṭṭhakathā", "aṭṭhasālinī", "dhammasaṅgaṇī"], related_name: "abhi1", abbr: "dha.sa.aṭṭha." },
  { id: 1780, book: 97, paragraph: 4, title: "vibhaṅga-aṭṭhakathā", sn: 103, toc: "Vibhaṅga-aṭṭhakathā", tags: ["abhidhamma", "aṭṭhakathā", "sammohavinodanī", "vibhaṅga"], related_name: "abhi2", abbr: "vibha.aṭṭha." },
  { id: 1781, book: 98, paragraph: 4, title: "dhātukathā-aṭṭhakathā", sn: 104, toc: "Dhātukathā-aṭṭhakathā", tags: ["abhidhamma", "aṭṭhakathā", "dhātukathā", "pañcapakaraṇa"], related_name: "abhi3", abbr: "dhātu.kathā.aṭṭha." },
  { id: 1782, book: 98, paragraph: 173, title: "puggalapaññatti-aṭṭhakathā", sn: 105, toc: "Puggalapaññatti-aṭṭhakathā", tags: ["abhidhamma", "aṭṭhakathā", "pañcapakaraṇa", "puggalapaññatti"], related_name: "abhi4", abbr: "puggala.paññatti.aṭṭha." },
  { id: 1783, book: 98, paragraph: 474, title: "kathāvatthu-aṭṭhakathā", sn: 106, toc: "Kathāvatthu-aṭṭhakathā", tags: ["abhidhamma", "aṭṭhakathā", "kathāvatthu", "pañcapakaraṇa"], related_name: "abhi5", abbr: "kathā.vatthu.aṭṭha." },
  { id: 1784, book: 98, paragraph: 1623, title: "yamakappakaraṇa-aṭṭhakathā", sn: 107, toc: "Yamakappakaraṇa-aṭṭhakathā", tags: ["abhidhamma", "aṭṭhakathā", "pañcapakaraṇa", "yamaka"], related_name: "abhi6", abbr: "yama.aṭṭha." },
  { id: 1785, book: 98, paragraph: 1880, title: "paṭṭhānappakaraṇa-aṭṭhakathā", sn: 108, toc: "Paṭṭhānappakaraṇa-aṭṭhakathā", tags: ["abhidhamma", "aṭṭhakathā", "pañcapakaraṇa", "paṭṭhāna"], related_name: "abhi7", abbr: "paṭṭhāna.aṭṭha." },
  { id: 1786, book: 99, paragraph: 3, title: "manorathapūraṇī", sn: 109, toc: "Ekakanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakathā", "ekakanipāta", "manorathapūraṇī", "nipāta", "sutta"], related_name: "an1_A", abbr: "a.ni.aṭṭha.1." },
  { id: 1787, book: 100, paragraph: 3, title: "manorathapūraṇī", sn: 110, toc: "Dukanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakathā", "dukanipāta", "manorathapūraṇī", "nipāta", "sutta"], related_name: "an2", abbr: "a.ni.aṭṭha.2." },
  { id: 1788, book: 100, paragraph: 325, title: "manorathapūraṇī", sn: 111, toc: "Tikanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakathā", "manorathapūraṇī", "nipāta", "sutta", "tikanipāta"], related_name: "an3", abbr: "a.ni.aṭṭha.3." },
  { id: 1789, book: 100, paragraph: 997, title: "manorathapūraṇī", sn: 112, toc: "Catukkanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakathā", "catukkanipāta", "manorathapūraṇī", "nipāta", "sutta"], related_name: "an4", abbr: "a.ni.aṭṭha.4." },
  { id: 1790, book: 101, paragraph: 3, title: "manorathapūraṇī", sn: 113, toc: "Pañcakanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakathā", "manorathapūraṇī", "nipāta", "pañcakanipāta", "sutta"], related_name: "an5", abbr: "a.ni.aṭṭha.5." },
  { id: 1791, book: 101, paragraph: 503, title: "manorathapūraṇī", sn: 114, toc: "Chakkanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakathā", "chakkanipāta", "manorathapūraṇī", "nipāta", "sutta"], related_name: "an6", abbr: "a.ni.aṭṭha.6." },
  { id: 1792, book: 101, paragraph: 792, title: "manorathapūraṇī", sn: 115, toc: "Sattakanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakathā", "manorathapūraṇī", "nipāta", "sattakanipāta", "sutta"], related_name: "an7", abbr: "a.ni.aṭṭha.7." },
  { id: 1793, book: 102, paragraph: 3, title: "manorathapūraṇī", sn: 116, toc: "Aṭṭhakanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakanipāta", "aṭṭhakathā", "manorathapūraṇī", "nipāta", "sutta"], related_name: "an8", abbr: "a.ni.aṭṭha.8." },
  { id: 1794, book: 102, paragraph: 275, title: "manorathapūraṇī", sn: 117, toc: "Navakanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakathā", "manorathapūraṇī", "navakanipāta", "nipāta", "sutta"], related_name: "an9", abbr: "a.ni.aṭṭha.9." },
  { id: 1795, book: 102, paragraph: 409, title: "manorathapūraṇī", sn: 118, toc: "Dasakanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakathā", "dasakanipāta", "manorathapūraṇī", "nipāta", "sutta"], related_name: "an10", abbr: "a.ni.aṭṭha.10." },
  { id: 1796, book: 102, paragraph: 706, title: "manorathapūraṇī", sn: 119, toc: "Ekādasakanipāta-aṭṭhakathā", tags: ["aṅguttaranikāya", "aṭṭhakathā", "ekādasakanipāta", "manorathapūraṇī", "nipāta", "sutta"], related_name: "an11", abbr: "a.ni.aṭṭha.11." },
  { id: 1797, book: 103, paragraph: 3, title: "sumaṅgalavilāsinī", sn: 120, toc: "(DN) Sīlakkhandhavaggaṭṭhakathā", tags: ["aṭṭhakathā", "dīghanikāya", "sumaṅgalavilāsinī", "sutta", "sīlakkhandhavagga"], related_name: "dn1_A", abbr: "dī.ni.aṭṭha.1." },
  { id: 1798, book: 104, paragraph: 3, title: "sumaṅgalavilāsinī", sn: 121, toc: "(DN) Mahāvaggaṭṭhakathā", tags: ["aṭṭhakathā", "dīghanikāya", "mahāvagga", "sumaṅgalavilāsinī", "sutta"], related_name: "dn2", abbr: "dī.ni.aṭṭha.2." },
  { id: 1799, book: 105, paragraph: 3, title: "sumaṅgalavilāsinī", sn: 122, toc: "(DN) Pāthikavaggaṭṭhakathā", tags: ["aṭṭhakathā", "dīghanikāya", "pāthikavagga", "sumaṅgalavilāsinī", "sutta"], related_name: "dn3", abbr: "dī.ni.aṭṭha.3." },
  { id: 1800, book: 106, paragraph: 3, title: "therīgāthā-aṭṭhakathā", sn: 123, toc: "Therīgāthā-aṭṭhakathā", tags: ["aṭṭhakathā", "khuddakanikāya", "sutta", "therīgāthā"], related_name: "kn9", abbr: "therī.aṭṭha." },
  { id: 1801, book: 107, paragraph: 3, title: "apadāna-aṭṭhakathā", sn: 124, toc: "Apadāna-aṭṭhakathā", tags: ["apadāna", "aṭṭhakathā", "khuddakanikāya", "sutta", "therāpadāna"], related_name: "kn10_A", abbr: "apa.aṭṭha." },
  { id: 1802, book: 108, paragraph: 3, title: "buddhavaṃsa-aṭṭhakathā", sn: 125, toc: "Buddhavaṃsa-aṭṭhakathā", tags: ["aṭṭhakathā", "buddhavaṃsa", "khuddakanikāya", "sutta", "vaṃsa ganthasaṅgaha"], related_name: "kn12", abbr: "buddhavaṃ.aṭṭha." },
  { id: 1803, book: 109, paragraph: 3, title: "cariyāpiṭaka-aṭṭhakathā", sn: 126, toc: "Cariyāpiṭaka-aṭṭhakathā", tags: ["aṭṭhakathā", "carita", "cariyāpiṭaka", "khuddakanikāya", "sutta"], related_name: "kn13", abbr: "cariyā.aṭṭha." },
  { id: 1804, book: 110, paragraph: 4, title: "jātaka-aṭṭhakathā", sn: 127, toc: "Jātaka-aṭṭhakathā(Paṭhamo bhāgo)", tags: ["aṭṭhakathā", "jātaka", "khuddakanikāya", "sutta"], related_name: "kn14", abbr: "jā.aṭṭha.1." },
  { id: 1805, book: 111, paragraph: 3, title: "jātaka-aṭṭhakathā", sn: 128, toc: "Jātaka-aṭṭhakathā(Dutiyo bhāgo)", tags: ["aṭṭhakathā", "jātaka", "khuddakanikāya", "sutta"], related_name: "kn14", abbr: "jā.aṭṭha.2." },
  { id: 1806, book: 112, paragraph: 4, title: "jātaka-aṭṭhakathā", sn: 129, toc: "Jātaka-aṭṭhakathā(Tatiyo bhāgo)", tags: ["aṭṭhakathā", "jātaka", "khuddakanikāya", "sutta"], related_name: "kn14", abbr: "jā.aṭṭha.3." },
  { id: 1807, book: 113, paragraph: 4, title: "jātaka-aṭṭhakathā", sn: 130, toc: "Jātaka-aṭṭhakathā(Catuttho bhāgo)", tags: ["aṭṭhakathā", "jātaka", "khuddakanikāya", "sutta"], related_name: "kn14", abbr: "jā.aṭṭha.4." },
  { id: 1808, book: 113, paragraph: 5312, title: "jātaka-aṭṭhakathā", sn: 131, toc: "Jātaka-aṭṭhakathā(Pañcamo bhāgo 16)", tags: ["aṭṭhakathā", "jātaka", "khuddakanikāya", "sutta"], related_name: "kn14", abbr: "jā.aṭṭha.5." },
  { id: 1809, book: 114, paragraph: 1, title: "jātaka-aṭṭhakathā", sn: 132, toc: "Jātaka-aṭṭhakathā(Pañcamo bhāgo 17-21)", tags: ["aṭṭhakathā", "jātaka", "khuddakanikāya", "sutta"], related_name: "kn14", abbr: "jā.aṭṭha.6." },
  { id: 1810, book: 115, paragraph: 3, title: "jātaka-aṭṭhakathā", sn: 133, toc: "Jātaka-aṭṭhakathā(Chaṭṭho bhāgo)", tags: ["aṭṭhakathā", "jātaka", "khuddakanikāya", "sutta"], related_name: "kn14", abbr: "jā.aṭṭha.7." },
  { id: 1811, book: 116, paragraph: 3, title: "khuddakapāṭha-aṭṭhakathā", sn: 134, toc: "Khuddakapāṭha-aṭṭhakathā", tags: ["aṭṭhakathā", "khuddakanikāya", "khuddakapāṭha", "paramatthajotika", "sutta"], related_name: "kn1", abbr: "khuddaka.aṭṭha." },
  { id: 1812, book: 117, paragraph: 3, title: "jātaka-aṭṭhakathā", sn: 135, toc: "Jātaka-aṭṭhakathā(Sattamo bhāgo)", tags: ["aṭṭhakathā", "jātaka", "khuddakanikāya", "sutta"], related_name: "kn14", abbr: "jā.aṭṭha.8." },
  { id: 1813, book: 118, paragraph: 3, title: "mahāniddesa-aṭṭhakathā", sn: 136, toc: "Mahāniddesa-aṭṭhakathā", tags: ["aṭṭhakathā", "khuddakanikāya", "mahāniddesa", "niddesa", "sutta"], related_name: "kn15", abbr: "mahāni.aṭṭha." },
  { id: 1814, book: 119, paragraph: 3, title: "cūḷaniddesa-aṭṭhakathā", sn: 137, toc: "Cūḷaniddesa-aṭṭhakathā", tags: ["aṭṭhakathā", "cūḷaniddesa", "khuddakanikāya", "niddesa", "sutta"], related_name: "kn16", abbr: "cūḷani.aṭṭha." },
  { id: 1815, book: 120, paragraph: 3, title: "paṭisambhidāmagga-aṭṭhakathā", sn: 138, toc: "Paṭisambhidāmagga-aṭṭhakathā", tags: ["aṭṭhakathā", "khuddakanikāya", "paṭisambhidāmagga", "saddhammappakāsinī", "sutta"], related_name: "kn17", abbr: "paṭi.ma.aṭṭha." },
  { id: 1816, book: 121, paragraph: 3, title: "nettippakaraṇa-aṭṭhakathā", sn: 139, toc: "Nettippakaraṇa-aṭṭhakathā", tags: ["aṭṭhakathā", "khuddakanikāya", "netti", "nettippakaraṇa", "sutta"], related_name: "kn19", abbr: "netti.aṭṭha." },
  { id: 1817, book: 122, paragraph: 3, title: "dhammapada-aṭṭhakathā", sn: 140, toc: "Dhammapada-aṭṭhakathā", tags: ["aṭṭhakathā", "dhammapada", "khuddakanikāya", "sutta"], related_name: "kn2", abbr: "dhamma.aṭṭha." },
  { id: 1818, book: 123, paragraph: 3, title: "udāna-aṭṭhakathā", sn: 141, toc: "Udāna-aṭṭhakathā", tags: ["aṭṭhakathā", "khuddakanikāya", "sutta", "udāna"], related_name: "kn3", abbr: "udāna.aṭṭha." },
  { id: 1819, book: 124, paragraph: 3, title: "itivuttaka-aṭṭhakathā", sn: 142, toc: "Itivuttaka-aṭṭhakathā", tags: ["aṭṭhakathā", "itivuttaka", "khuddakanikāya", "sutta"], related_name: "kn4", abbr: "itivutta.aṭṭha." },
  { id: 1820, book: 125, paragraph: 3, title: "suttanipāta-aṭṭhakathā", sn: 143, toc: "Suttanipāta-aṭṭhakathā", tags: ["aṭṭhakathā", "khuddakanikāya", "nipāta", "paramatthajotika", "sutta", "suttanipāta"], related_name: "kn5", abbr: "suttani.aṭṭha." },
  { id: 1821, book: 126, paragraph: 3, title: "vimānavatthu-aṭṭhakathā", sn: 144, toc: "Vimānavatthu-aṭṭhakathā", tags: ["aṭṭhakathā", "khuddakanikāya", "sutta", "vimānavatthu"], related_name: "kn6", abbr: "vimāna.aṭṭha." },
  { id: 1822, book: 127, paragraph: 3, title: "petavatthu-aṭṭhakathā", sn: 145, toc: "Petavatthu-aṭṭhakathā", tags: ["aṭṭhakathā", "khuddakanikāya", "petavatthu", "sutta"], related_name: "kn7", abbr: "peta.aṭṭha." },
  { id: 1823, book: 128, paragraph: 3, title: "theragāthā-aṭṭhakathā", sn: 146, toc: "Theragāthā-aṭṭhakathā(Paṭhamo bhāgo)", tags: ["aṭṭhakathā", "khuddakanikāya", "sutta", "theragāthā"], related_name: "kn8", abbr: "thera.aṭṭha.1." },
  { id: 1824, book: 129, paragraph: 3, title: "theragāthā-aṭṭhakathā", sn: 147, toc: "Theragāthā-aṭṭhakathā(Dutiyo bhāgo)", tags: ["aṭṭhakathā", "khuddakanikāya", "sutta", "theragāthā"], related_name: "kn8", abbr: "thera.aṭṭha.2." },
  { id: 1825, book: 130, paragraph: 3, title: "papañcasūdanī", sn: 148, toc: "(MN) Mūlapaṇṇāsa-aṭṭhakathā", tags: ["aṭṭhakathā", "majjhimanikāya", "mūlapaṇṇāsa", "papañcasūdanī", "sutta"], related_name: "mn1_A", abbr: "ma.ni.aṭṭha.1." },
  { id: 1826, book: 131, paragraph: 3, title: "papañcasūdanī", sn: 149, toc: "(MN) Majjhimapaṇṇāsa-aṭṭhakathā", tags: ["aṭṭhakathā", "majjhimanikāya", "majjhimapaṇṇāsa", "papañcasūdanī", "sutta"], related_name: "mn2", abbr: "ma.ni.aṭṭha.2." },
  { id: 1827, book: 132, paragraph: 3, title: "papañcasūdanī", sn: 150, toc: "(MN) Uparipaṇṇāsa-aṭṭhakathā", tags: ["aṭṭhakathā", "majjhimanikāya", "papañcasūdanī", "sutta", "uparipaṇṇāsa"], related_name: "mn3", abbr: "ma.ni.aṭṭha.3." },
  { id: 1828, book: 133, paragraph: 3, title: "sāratthappakāsinī", sn: 151, toc: "(SN) Sagāthāvagga-aṭṭhakathā", tags: ["aṭṭhakathā", "sagāthāvagga", "saṃyuttanikāya", "sutta", "sāratthappakāsinī"], related_name: "sn1_A", abbr: "saṃ.ni.aṭṭha.1." },
  { id: 1829, book: 134, paragraph: 3, title: "sāratthappakāsinī", sn: 152, toc: "(SN) Nidānavagga-aṭṭhakathā", tags: ["aṭṭhakathā", "nidānavagga", "saṃyuttanikāya", "sutta", "sāratthappakāsinī"], related_name: "sn2", abbr: "saṃ.ni.aṭṭha.2." },
  { id: 1830, book: 135, paragraph: 3, title: "sāratthappakāsinī", sn: 153, toc: "(SN) Khandhavagga-aṭṭhakathā", tags: ["aṭṭhakathā", "khandhavagga", "saṃyuttanikāya", "sutta", "sāratthappakāsinī"], related_name: "sn3", abbr: "saṃ.ni.aṭṭha.3." },
  { id: 1831, book: 136, paragraph: 3, title: "sāratthappakāsinī", sn: 154, toc: "(SN) Saḷāyatanavagga-aṭṭhakathā", tags: ["aṭṭhakathā", "saḷāyatanavagga", "saṃyuttanikāya", "sutta", "sāratthappakāsinī"], related_name: "sn4", abbr: "saṃ.ni.aṭṭha.4." },
  { id: 1832, book: 137, paragraph: 3, title: "sāratthappakāsinī", sn: 155, toc: "(SN) Mahāvagga-aṭṭhakathā", tags: ["aṭṭhakathā", "mahāvagga", "saṃyuttanikāya", "sutta", "sāratthappakāsinī"], related_name: "sn5", abbr: "saṃ.ni.aṭṭha.5." },
  { id: 1833, book: 138, paragraph: 3, title: "samantapāsādikā", sn: 156, toc: "Pārājikakaṇḍa-aṭṭhakathā", tags: ["aṭṭhakathā", "mahāvibhaṅga", "pārājika", "pārājikakaṇḍa", "samantapāsādikā", "suttavibhaṅga", "vinaya"], related_name: "vin1", abbr: "pārā.aṭṭha." },
  { id: 1834, book: 139, paragraph: 3, title: "samantapāsādikā", sn: 157, toc: "(SP) Pācittiya-aṭṭhakathā", tags: ["aṭṭhakathā", "mahāvibhaṅga", "pācittiya", "pācittiya-aṭṭhakathā", "samantapāsādikā", "suttavibhaṅga", "vinaya"], related_name: "vin2", abbr: "pāci.aṭṭha." },
  { id: 1835, book: 140, paragraph: 3, title: "samantapāsādikā", sn: 158, toc: "(SP) Mahāvagga-aṭṭhakathā", tags: ["aṭṭhakathā", "khandhaka", "mahāvagga", "samantapāsādikā", "vinaya"], related_name: "vin3", abbr: "mahāva.aṭṭha." },
  { id: 1836, book: 141, paragraph: 3, title: "samantapāsādikā", sn: 159, toc: "(SP) Cūḷavagga-aṭṭhakathā", tags: ["aṭṭhakathā", "cūḷavagga", "khandhaka", "samantapāsādikā", "vinaya"], related_name: "vin4", abbr: "cūḷava.aṭṭha." },
  { id: 1837, book: 142, paragraph: 3, title: "samantapāsādikā", sn: 160, toc: "(SP) Parivāra-aṭṭhakathā", tags: ["aṭṭhakathā", "parivāra", "parivārapāḷi", "samantapāsādikā", "vinaya"], related_name: "vin5", abbr: "pari.aṭṭha." },
  { id: 1838, book: 143, paragraph: 3, title: "therāpadānapāḷi", sn: 161, toc: "Therāpadānapāḷi(Paṭhamo bhāgo)", tags: ["apadāna", "khuddakanikāya", "mūla", "pāḷi", "sutta", "therāpadāna"], related_name: "kn10_A", abbr: "apa.1." },
  { id: 1839, book: 144, paragraph: 3, title: "therāpadānapāḷi", sn: 162, toc: "Therāpadānapāḷi(Dutiyo bhāgo)", tags: ["apadāna", "khuddakanikāya", "mūla", "pāḷi", "sutta", "therāpadāna"], related_name: "kn10_B", abbr: "apa.2." },
  { id: 1840, book: 144, paragraph: 6534, title: "therīapadānapāḷi", sn: 163, toc: "Therīapadānapāḷi", tags: ["apadāna", "khuddakanikāya", "mūla", "pāḷi", "sutta", "therīapadāna"], related_name: "kn10_B", abbr: "therī.apa." },
  { id: 1841, book: 145, paragraph: 3, title: "buddhavaṃsapāḷi", sn: 164, toc: "Buddhavaṃsapāḷi", tags: ["buddhavaṃsa", "khuddakanikāya", "mūla", "pāḷi", "sutta", "vaṃsa ganthasaṅgaha"], related_name: "kn12", abbr: "buddhavaṃ." },
  { id: 1842, book: 146, paragraph: 3, title: "cariyāpiṭakapāḷi", sn: 165, toc: "Cariyāpiṭakapāḷi", tags: ["carita", "cariyāpiṭaka", "khuddakanikāya", "mūla", "pāḷi", "sutta"], related_name: "kn13", abbr: "cariyā." },
  { id: 1843, book: 147, paragraph: 3, title: "jātakapāḷi", sn: 166, toc: "Jātakapāḷi(Dutiyo bhāgo)", tags: ["jātaka", "khuddakanikāya", "mūla", "pāḷi", "sutta"], related_name: "kn14", abbr: "jā.2." },
  { id: 1844, book: 148, paragraph: 3, title: "jātakapāḷi", sn: 167, toc: "Jātakapāḷi(Paṭhamo bhāgo)", tags: ["jātaka", "khuddakanikāya", "mūla", "pāḷi", "sutta"], related_name: "kn14", abbr: "jā.1." },
  { id: 1845, book: 149, paragraph: 3, title: "mahāniddesapāḷi", sn: 168, toc: "Mahāniddesapāḷi", tags: ["khuddakanikāya", "mahāniddesa", "mūla", "niddesa", "pāḷi", "sutta"], related_name: "kn15", abbr: "mahāni." },
  { id: 1846, book: 150, paragraph: 3, title: "cūḷaniddesapāḷi", sn: 169, toc: "Cūḷaniddesapāḷi", tags: ["cūḷaniddesa", "khuddakanikāya", "mūla", "niddesa", "pāḷi", "sutta"], related_name: "kn16", abbr: "cūḷani." },
  { id: 1847, book: 151, paragraph: 3, title: "paṭisambhidāmaggapāḷi", sn: 170, toc: "Paṭisambhidāmaggapāḷi", tags: ["khuddakanikāya", "mūla", "paṭisambhidāmagga", "pāḷi", "sutta"], related_name: "kn17", abbr: "paṭi.ma." },
  { id: 1848, book: 152, paragraph: 3, title: "milindapañhapāḷi", sn: 171, toc: "Milindapañhapāḷi", tags: ["khuddakanikāya", "milindapañha", "mūla", "pāḷi", "sutta"], related_name: "kn18", abbr: "milinda." },
  { id: 1849, book: 153, paragraph: 3, title: "nettippakaraṇapāḷi", sn: 172, toc: "Nettippakaraṇapāḷi", tags: ["khuddakanikāya", "mūla", "netti", "nettippakaraṇa", "pāḷi", "sutta"], related_name: "kn19", abbr: "netti." },
  { id: 1850, book: 154, paragraph: 3, title: "khuddakapāṭhapāḷi", sn: 173, toc: "Khuddakapāṭhapāḷi", tags: ["khuddakanikāya", "khuddakapāṭha", "mūla", "pāḷi", "sutta"], related_name: "kn1", abbr: "khuddaka." },
  { id: 1851, book: 155, paragraph: 3, title: "peṭakopadesapāḷi", sn: 174, toc: "Peṭakopadesapāḷi", tags: ["khuddakanikāya", "mūla", "peṭakopadesa", "pāḷi", "sutta"], related_name: "kn20", abbr: "peṭako." },
  { id: 1852, book: 156, paragraph: 3, title: "dhammapadapāḷi", sn: 175, toc: "Dhammapadapāḷi", tags: ["dhammapada", "khuddakanikāya", "mūla", "pāḷi", "sutta"], related_name: "kn2", abbr: "dhamma." },
  { id: 1853, book: 157, paragraph: 3, title: "udānapāḷi", sn: 176, toc: "Udānapāḷi", tags: ["khuddakanikāya", "mūla", "pāḷi", "sutta", "udāna"], related_name: "kn3", abbr: "udāna." },
  { id: 1854, book: 158, paragraph: 3, title: "itivuttakapāḷi", sn: 177, toc: "Itivuttakapāḷi", tags: ["itivuttaka", "khuddakanikāya", "mūla", "pāḷi", "sutta"], related_name: "kn4", abbr: "itivutta." },
  { id: 1855, book: 159, paragraph: 3, title: "suttanipātapāḷi", sn: 178, toc: "Suttanipātapāḷi", tags: ["khuddakanikāya", "mūla", "nipāta", "pāḷi", "sutta", "suttanipāta"], related_name: "kn5", abbr: "suttani." },
  { id: 1856, book: 160, paragraph: 3, title: "vimānavatthupāḷi", sn: 179, toc: "Vimānavatthupāḷi", tags: ["khuddakanikāya", "mūla", "pāḷi", "sutta", "vimānavatthu"], related_name: "kn6", abbr: "vimāna." },
  { id: 1857, book: 161, paragraph: 3, title: "petavatthupāḷi", sn: 180, toc: "Petavatthupāḷi", tags: ["khuddakanikāya", "mūla", "petavatthu", "pāḷi", "sutta"], related_name: "kn7", abbr: "peta." },
  { id: 1858, book: 162, paragraph: 3, title: "theragāthāpāḷi", sn: 181, toc: "Theragāthāpāḷi", tags: ["khuddakanikāya", "mūla", "pāḷi", "sutta", "theragāthā"], related_name: "kn8", abbr: "theragāthā." },
  { id: 1859, book: 163, paragraph: 3, title: "therīgāthāpāḷi", sn: 182, toc: "Therīgāthāpāḷi", tags: ["khuddakanikāya", "mūla", "pāḷi", "sutta", "therīgāthā"], related_name: "kn9", abbr: "therī." },
  { id: 1860, book: 164, paragraph: 3, title: "majjhimanikāyapāḷi", sn: 183, toc: "(MN)Mūlapaṇṇāsapāḷi", tags: ["majjhimanikāya", "mūla", "mūlapaṇṇāsa", "pāḷi", "sutta"], related_name: "mn1", abbr: "ma.ni.1." },
  { id: 1861, book: 165, paragraph: 3, title: "majjhimanikāyapāḷi", sn: 184, toc: "(MN)Majjhimapaṇṇāsapāḷi", tags: ["majjhimanikāya", "majjhimapaṇṇāsa", "mūla", "pāḷi", "sutta"], related_name: "mn2", abbr: "ma.ni.2." },
  { id: 1862, book: 166, paragraph: 3, title: "majjhimanikāyapāḷi", sn: 185, toc: "(MN)Uparipaṇṇāsapāḷi", tags: ["majjhimanikāya", "mūla", "pāḷi", "sutta", "uparipaṇṇāsa"], related_name: "mn3", abbr: "ma.ni.3." },
  { id: 1863, book: 167, paragraph: 3, title: "saṃyuttanikāyapāḷi", sn: 186, toc: "(SN)Sagāthāvaggo", tags: ["mūla", "pāḷi", "sagāthāvagga", "saṃyuttanikāya", "sutta"], related_name: "sn1", abbr: "saṃ.ni.1." },
  { id: 1864, book: 168, paragraph: 3, title: "saṃyuttanikāyapāḷi", sn: 187, toc: "(SN)Nidānavaggo", tags: ["mūla", "nidānavagga", "pāḷi", "saṃyuttanikāya", "sutta"], related_name: "sn2", abbr: "saṃ.ni.2." },
  { id: 1865, book: 169, paragraph: 3, title: "saṃyuttanikāyapāḷi", sn: 188, toc: "(SN)Khandhavaggo", tags: ["khandhavagga", "mūla", "pāḷi", "saṃyuttanikāya", "sutta"], related_name: "sn3", abbr: "saṃ.ni.3." },
  { id: 1866, book: 170, paragraph: 3, title: "saṃyuttanikāyapāḷi", sn: 189, toc: "(SN)Saḷāyatanavaggo", tags: ["mūla", "pāḷi", "saḷāyatanavagga", "saṃyuttanikāya", "sutta"], related_name: "sn4", abbr: "saṃ.ni.4." },
  { id: 1867, book: 171, paragraph: 3, title: "saṃyuttanikāyapāḷi", sn: 190, toc: "(SN)Mahāvaggo", tags: ["mahāvagga", "mūla", "pāḷi", "saṃyuttanikāya", "sutta"], related_name: "sn5", abbr: "saṃ.ni.5." },
  { id: 1868, book: 172, paragraph: 3, title: "mūlaṭīkā", sn: 191, toc: "Dhammasaṅgaṇī-mūlaṭīkā", tags: ["abhidhamma", "dhammasaṅgaṇī", "mūlaṭīkā", "ṭīkā"], related_name: "abhi1", abbr: "dha.sa.mūlaṭī." },
  { id: 1869, book: 173, paragraph: 3, title: "mūlaṭīkā", sn: 192, toc: "Vibhaṅga-mūlaṭīkā", tags: ["abhidhamma", "mūlaṭīkā", "vibhaṅga", "ṭīkā"], related_name: "abhi2", abbr: "vibha.mūlaṭī." },
  { id: 1870, book: 173, paragraph: 1155, title: "anuṭīkā", sn: 193, toc: "Vibhaṅga-anuṭīkā", tags: ["abhidhamma", "mūlaṭīkā", "vibhaṅga", "ṭīkā"], related_name: "abhi2", abbr: "vibha.anuṭī." },
  { id: 1871, book: 174, paragraph: 4, title: "mūlaṭīkā", sn: 194, toc: "Dhātukathāpakaraṇa-mūlaṭīkā", tags: ["abhidhamma", "dhātukathā", "mūlaṭīkā", "pañcapakaraṇa", "ṭīkā"], related_name: "abhi3", abbr: "dhātu.kathā.mūlaṭī." },
  { id: 1872, book: 174, paragraph: 100, title: "mūlaṭīkā", sn: 195, toc: "Puggalapaññattipakaraṇa-mūlaṭīkā", tags: ["abhidhamma", "mūlaṭīkā", "pañcapakaraṇa", "puggalapaññatti", "ṭīkā"], related_name: "abhi4", abbr: "puggala.paññatti.mūlaṭī." },
  { id: 1873, book: 174, paragraph: 201, title: "mūlaṭīkā", sn: 196, toc: "Kathāvatthupakaraṇa-mūlaṭīkā", tags: ["abhidhamma", "kathāvatthu", "mūlaṭīkā", "pañcapakaraṇa", "ṭīkā"], related_name: "abhi5", abbr: "kathā.vatthu.mūlaṭī." },
  { id: 1874, book: 174, paragraph: 865, title: "mūlaṭīkā", sn: 197, toc: "Yamakapakaraṇa-mūlaṭīkā", tags: ["abhidhamma", "mūlaṭīkā", "pañcapakaraṇa", "yamaka", "ṭīkā"], related_name: "abhi6", abbr: "yama.mūlaṭī." },
  { id: 1875, book: 174, paragraph: 1059, title: "mūlaṭīkā", sn: 198, toc: "Paṭṭhānapakaraṇa-mūlaṭīkā", tags: ["abhidhamma", "mūlaṭīkā", "pañcapakaraṇa", "paṭṭhāna", "ṭīkā"], related_name: "abhi7", abbr: "paṭṭhāna.mūlaṭī." },
  { id: 1876, book: 175, paragraph: 3, title: "anuṭīkā", sn: 199, toc: "Dhammasaṅgaṇī-anuṭīkā", tags: ["abhidhamma", "anuṭīkā", "dhammasaṅgaṇī", "ṭīkā"], related_name: "abhi1", abbr: "dha.sa.anuṭī." },
  { id: 1877, book: 176, paragraph: 4, title: "anuṭīkā", sn: 200, toc: "Dhātukathāpakaraṇa-anuṭīkā", tags: ["abhidhamma", "anuṭīkā", "dhātukathā", "pañcapakaraṇa", "ṭīkā"], related_name: "abhi3", abbr: "dhātu.kathā.anuṭī." },
  { id: 1878, book: 176, paragraph: 117, title: "anuṭīkā", sn: 201, toc: "Puggalapaññattipakaraṇa-anuṭīkā", tags: ["abhidhamma", "anuṭīkā", "pañcapakaraṇa", "puggalapaññatti", "ṭīkā"], related_name: "abhi4", abbr: "puggala.paññatti.anuṭī." },
  { id: 1879, book: 176, paragraph: 213, title: "anuṭīkā", sn: 202, toc: "Kathāvatthupakaraṇa-anuṭīkā", tags: ["abhidhamma", "anuṭīkā", "kathāvatthu", "pañcapakaraṇa", "ṭīkā"], related_name: "abhi5", abbr: "kathā.vatthu.anuṭī." },
  { id: 1880, book: 176, paragraph: 917, title: "anuṭīkā", sn: 203, toc: "Yamakapakaraṇa-anuṭīkā", tags: ["abhidhamma", "anuṭīkā", "pañcapakaraṇa", "yamaka", "ṭīkā"], related_name: "abhi6", abbr: "yama.anuṭī." },
  { id: 1881, book: 176, paragraph: 1139, title: "anuṭīkā", sn: 204, toc: "Paṭṭhānapakaraṇa-anuṭīkā", tags: ["abhidhamma", "anuṭīkā", "pañcapakaraṇa", "paṭṭhāna", "ṭīkā"], related_name: "abhi7", abbr: "paṭṭhāna.anuṭī." },
  { id: 1882, book: 177, paragraph: 2, title: "abhidhammāvatāro", sn: 205, toc: "Abhidhammāvatāro", tags: ["abhidhamma", "abhidhammāvatāra", "abhidhammāvatāro", "ṭīkā"], related_name: "abhi8", abbr: "abhidhammāvatāra." },
  { id: 1883, book: 177, paragraph: 4805, title: "nāmarūpaparicchedo", sn: 206, toc: "Nāmarūpaparicchedo", tags: ["abhidhamma", "abhidhammāvatāro", "nāmarūpapariccheda", "ṭīkā"], related_name: null, abbr: "nāmarūpapariccheda." },
  { id: 1884, book: 177, paragraph: 10627, title: "paramatthavinicchayo", sn: 207, toc: "Paramatthavinicchayo", tags: ["abhidhamma", "abhidhammāvatāro", "paramatthavinicchaya", "ṭīkā"], related_name: null, abbr: "paramatthavinicchaya." },
  { id: 1885, book: 177, paragraph: 14272, title: "saccasaṅkhepo", sn: 208, toc: "Saccasaṅkhepo", tags: ["abhidhamma", "abhidhammāvatāro", "saccasaṅkhepa", "ṭīkā"], related_name: null, abbr: "saccasaṅkhepa." },
  { id: 1886, book: 178, paragraph: 2, title: "abhidhammatthasaṅgaho", sn: 209, toc: "Abhidhammatthasaṅgaho", tags: ["abhidhamma", "abhidhammatthasaṅgaha", "ṭīkā"], related_name: "abhi9", abbr: "abhidhammatthasaṅgaha." },
  { id: 1887, book: 178, paragraph: 875, title: "abhidhammatthavibhāvinīṭīkā", sn: 210, toc: "Abhidhammatthavibhāvinīṭīkā", tags: ["abhidhamma", "abhidhammatthasaṅgaha", "ṭīkā"], related_name: "abhi9", abbr: "abhidhammatthavibhāvinī.ṭī." },
  { id: 1888, book: 179, paragraph: 2, title: "abhidhammāvatāra-purāṇaṭīkā", sn: 211, toc: "Abhidhammāvatāra-purāṇaṭīkā", tags: ["abhidhamma", "abhidhammāvatāra", "avatāra", "purāṇaṭīkā", "ṭīkā"], related_name: "abhi8", abbr: "abhidhammāvatāra.purāṇaṭī." },
  { id: 1889, book: 179, paragraph: 872, title: "abhidhammāvatāra-abhinavaṭīkā", sn: 212, toc: "Abhidhammāvatāra-abhinavaṭīkā", tags: ["abhidhamma", "abhidhammāvatāra", "abhinavaṭīkā", "avatāra", "ṭīkā"], related_name: "abhi8", abbr: "abhidhammāvatāra.abhinavaṭī." },
  { id: 1890, book: 180, paragraph: 2, title: "abhidhammamātikāpāḷi", sn: 213, toc: "Abhidhammamātikāpāḷi", tags: ["abhidhamma", "abhidhammamātikā", "abhidhammamātikāpāḷi", "mātikā", "pāḷi", "ṭīkā"], related_name: null, abbr: "abhidhammamātikā." },
  { id: 1891, book: 180, paragraph: 1221, title: "mohavicchedanī", sn: 214, toc: "Mohavicchedanī", tags: ["abhidhamma", "abhidhammamātikā", "mohavicchedanī", "mātikā", "pāḷi", "ṭīkā"], related_name: null, abbr: "mohavicchedanī." },
  { id: 1892, book: 181, paragraph: 3, title: "ekakanipāta-ṭīkā", sn: 215, toc: "Ekakanipāta-ṭīkā", tags: ["aṅguttaranikāya", "ekakanipāta", "nipāta", "sutta", "sāratthamañjūsā", "ṭīkā"], related_name: "an1_A", abbr: "a.ni.ṭī.1." },
  { id: 1893, book: 182, paragraph: 3, title: "dukanipāta-ṭīkā", sn: 216, toc: "Dukanipāta-ṭīkā", tags: ["aṅguttaranikāya", "dukanipāta", "nipāta", "sutta", "sāratthamañjūsā", "ṭīkā"], related_name: "an2", abbr: "a.ni.ṭī.2." },
  { id: 1894, book: 182, paragraph: 324, title: "tikanipāta-ṭīkā", sn: 217, toc: "Tikanipāta-ṭīkā", tags: ["aṅguttaranikāya", "nipāta", "sutta", "sāratthamañjūsā", "tikanipāta", "ṭīkā"], related_name: "an3", abbr: "a.ni.ṭī.3." },
  { id: 1895, book: 182, paragraph: 1023, title: "catukkanipāta-ṭīkā", sn: 218, toc: "Catukkanipāta-ṭīkā", tags: ["aṅguttaranikāya", "catukkanipāta", "nipāta", "sutta", "sāratthamañjūsā", "ṭīkā"], related_name: "an4", abbr: "a.ni.ṭī.4." },
  { id: 1896, book: 183, paragraph: 3, title: "pañcakanipāta-ṭīkā", sn: 219, toc: "Pañcakanipāta-ṭīkā", tags: ["aṅguttaranikāya", "nipāta", "pañcakanipāta", "sutta", "sāratthamañjūsā", "ṭīkā"], related_name: "an5", abbr: "a.ni.ṭī.5." },
  { id: 1897, book: 183, paragraph: 470, title: "chakkanipāta-ṭīkā", sn: 220, toc: "Chakkanipāta-ṭīkā", tags: ["aṅguttaranikāya", "chakkanipāta", "nipāta", "sutta", "sāratthamañjūsā", "ṭīkā"], related_name: "an6", abbr: "a.ni.ṭī.6." },
  { id: 1898, book: 183, paragraph: 793, title: "sattakanipāta-ṭīkā", sn: 221, toc: "Sattakanipāta-ṭīkā", tags: ["aṅguttaranikāya", "nipāta", "sattakanipāta", "sutta", "sāratthamañjūsā", "ṭīkā"], related_name: "an7", abbr: "a.ni.ṭī.7." },
  { id: 1899, book: 184, paragraph: 3, title: "aṭṭhakanipāta-ṭīkā", sn: 222, toc: "Aṭṭhakanipāta-ṭīkā", tags: ["aṅguttaranikāya", "aṭṭhakanipāta", "nipāta", "sutta", "sāratthamañjūsā", "ṭīkā"], related_name: "an8", abbr: "a.ni.ṭī.8." },
  { id: 1900, book: 184, paragraph: 278, title: "navakanipāta-ṭīkā", sn: 223, toc: "Navakanipāta-ṭīkā", tags: ["aṅguttaranikāya", "navakanipāta", "nipāta", "sutta", "sāratthamañjūsā", "ṭīkā"], related_name: "an9", abbr: "a.ni.ṭī.9." },
  { id: 1901, book: 184, paragraph: 466, title: "dasakanipāta-ṭīkā", sn: 224, toc: "Dasakanipāta-ṭīkā", tags: ["aṅguttaranikāya", "dasakanipāta", "nipāta", "sutta", "sāratthamañjūsā", "ṭīkā"], related_name: "an10", abbr: "a.ni.ṭī.10." },
  { id: 1902, book: 184, paragraph: 776, title: "ekādasakanipāta-ṭīkā", sn: 225, toc: "Ekādasakanipāta-ṭīkā", tags: ["aṅguttaranikāya", "ekādasakanipāta", "nipāta", "sutta", "sāratthamañjūsā", "ṭīkā"], related_name: "an11", abbr: "a.ni.ṭī.11." },
  { id: 1903, book: 185, paragraph: 3, title: "līnatthappakāsanā", sn: 226, toc: "(DN)Sīlakkhandhavaggaṭīkā", tags: ["dīghanikāya", "līnatthappakāsanā", "sutta", "sīlakkhandhavagga", "sīlakkhandhavaggaṭīkā", "ṭīkā"], related_name: "dn1_A", abbr: "dī.ni.ṭī.1." },
  { id: 1904, book: 186, paragraph: 3, title: "līnatthappakāsanā", sn: 227, toc: "(DN)Mahāvaggaṭīkā", tags: ["dīghanikāya", "līnatthappakāsanā", "mahāvagga", "sutta", "ṭīkā"], related_name: "dn2", abbr: "dī.ni.ṭī.2." },
  { id: 1905, book: 187, paragraph: 3, title: "līnatthappakāsanā", sn: 228, toc: "(DN)Pāthikavaggaṭīkā", tags: ["dīghanikāya", "līnatthappakāsanā", "pāthikavagga", "sutta", "ṭīkā"], related_name: "dn3", abbr: "dī.ni.ṭī.3." },
  { id: 1906, book: 188, paragraph: 3, title: "sādhuvilāsinī", sn: 229, toc: "(DN)Sīlakkhandhavaggaabhinavaṭīkā", tags: ["abhinavaṭīkā", "dīghanikāya", "sutta", "sādhuvilāsinī", "sīlakkhandhavagga", "ṭīkā"], related_name: "dn1_A", abbr: "dī.ni.abhi.ṭī.1." },
  { id: 1907, book: 189, paragraph: 3, title: "sādhuvilāsinī", sn: 230, toc: "(DN)Sīlakkhandhavaggaabhinavaṭīkā", tags: ["abhinavaṭīkā", "dīghanikāya", "sutta", "sādhuvilāsinī", "sīlakkhandhavagga", "ṭīkā"], related_name: "dn1", abbr: "dī.ni.abhi.ṭī.2." },
  { id: 1908, book: 190, paragraph: 3, title: "nettippakaraṇa-ṭīkā", sn: 231, toc: "Nettippakaraṇa-ṭīkā", tags: ["khuddakanikāya", "netti", "nettippakaraṇa", "sutta", "ṭīkā"], related_name: "kn19", abbr: "netti.ṭī." },
  { id: 1909, book: 191, paragraph: 3, title: "nettivibhāvinī", sn: 232, toc: "Nettivibhāvinī", tags: ["khuddakanikāya", "netti", "nettivibhāvinī", "sutta", "ṭīkā"], related_name: "kn19", abbr: "netti.vibhā." },
  { id: 1910, book: 192, paragraph: 3, title: "līnatthappakāsanā", sn: 233, toc: "(MN)Mūlapaṇṇāsa-ṭīkā", tags: ["līnatthappakāsanā", "majjhimanikāya", "mūlapaṇṇāsa", "sutta", "ṭīkā"], related_name: "mn1_A", abbr: "ma.ni.ṭī.1." },
  { id: 1911, book: 193, paragraph: 3, title: "līnatthappakāsanā", sn: 234, toc: "(MN)Majjhimapaṇṇāsa-ṭīkā", tags: ["līnatthappakāsanā", "majjhimanikāya", "majjhimapaṇṇāsa", "sutta", "ṭīkā"], related_name: "mn2", abbr: "ma.ni.ṭī.2." },
  { id: 1912, book: 194, paragraph: 3, title: "līnatthappakāsanā", sn: 235, toc: "(MN)Uparipaṇṇāsa-ṭīkā", tags: ["līnatthappakāsanā", "majjhimanikāya", "sutta", "uparipaṇṇāsa", "ṭīkā"], related_name: "mn3", abbr: "ma.ni.ṭī.3." },
  { id: 1913, book: 195, paragraph: 3, title: "līnatthappakāsanā", sn: 236, toc: "(SN)Sagāthāvagga-ṭīkā", tags: ["līnatthappakāsanā", "sagāthāvagga", "saṃyuttanikāya", "sutta", "ṭīkā"], related_name: "sn1", abbr: "saṃ.ni.ṭī.1." },
  { id: 1914, book: 196, paragraph: 3, title: "līnatthappakāsanā", sn: 237, toc: "(SN)Nidānavagga-ṭīkā", tags: ["līnatthappakāsanā", "nidānavagga", "saṃyuttanikāya", "sutta", "ṭīkā"], related_name: "sn2", abbr: "saṃ.ni.ṭī.2." },
  { id: 1915, book: 197, paragraph: 3, title: "līnatthappakāsanā", sn: 238, toc: "(SN)Khandhavagga-ṭīkā", tags: ["khandhavagga", "līnatthappakāsanā", "saṃyuttanikāya", "sutta", "ṭīkā"], related_name: "sn3", abbr: "saṃ.ni.ṭī.3." },
  { id: 1916, book: 198, paragraph: 3, title: "līnatthappakāsanā", sn: 239, toc: "(SN)Saḷāyatanavagga-ṭīkā", tags: ["līnatthappakāsanā", "saḷāyatanavagga", "saṃyuttanikāya", "sutta", "ṭīkā"], related_name: "sn4", abbr: "saṃ.ni.ṭī.4." },
  { id: 1917, book: 199, paragraph: 3, title: "līnatthappakāsanā", sn: 240, toc: "(SN)Mahāvagga-ṭīkā", tags: ["līnatthappakāsanā", "mahāvagga", "saṃyuttanikāya", "sutta", "ṭīkā"], related_name: "sn5", abbr: "saṃ.ni.ṭī.5." },
  { id: 1918, book: 200, paragraph: 2, title: "vinayavinicchayo", sn: 241, toc: "Vinayavinicchayo", tags: ["vinaya", "vinayavinicchaya", "vinicchaya", "ṭīkā"], related_name: "vin8", abbr: "vinayavinicchaya." },
  { id: 1919, book: 200, paragraph: 10176, title: "uttaravinicchayo", sn: 242, toc: "Uttaravinicchayo", tags: ["uttaravinicchaya", "vinaya", "vinicchaya", "ṭīkā"], related_name: "vin9", abbr: "uttaravinicchaya." },
  { id: 1920, book: 201, paragraph: 2, title: "vinayavinicchaya-ṭīkā", sn: 243, toc: "Vinayavinicchaya-ṭīkā", tags: ["vinaya", "vinayavinicchaya", "vinayavinicchayaṭīkā", "vinicchaya", "ṭīkā"], related_name: "vin8", abbr: "vinayavinicchaya.ṭī." },
  { id: 1921, book: 201, paragraph: 4270, title: "uttaravinicchaya-ṭīkā", sn: 244, toc: "Uttaravinicchaya-ṭīkā", tags: ["uttaravinicchaya", "uttaravinicchayaṭīkā", "vinaya", "vinicchaya", "ṭīkā"], related_name: "vin9", abbr: "uttaravinicchaya.ṭī." },
  { id: 1922, book: 202, paragraph: 3, title: "pācityādiyojanā", sn: 245, toc: "Pācityādiyojanā", tags: ["pācittiyapāḷi", "pācityādiyojanā", "suttavibhaṅga", "uttaravinicchayaṭīkā", "vinaya", "yojanā", "ṭīkā"], related_name: "vin2", abbr: "pācityādiyojanā." },
  { id: 1923, book: 203, paragraph: 3, title: "khuddasikkhā", sn: 246, toc: "Khuddasikkhā", tags: ["khuddasikkhā", "vinaya", "ṭīkā"], related_name: "vin10", abbr: "khuddasikkhā." },
  { id: 1924, book: 203, paragraph: 1620, title: "khuddasikkhā", sn: 247, toc: "Khuddasikkhā-purāṇaṭīkā", tags: ["khuddasikkhā", "purāṇaṭīkā", "vinaya", "ṭīkā"], related_name: "vin10", abbr: "khuddasikkhā.purāṇaṭī." },
  { id: 1925, book: 203, paragraph: 2361, title: "khuddasikkhā", sn: 248, toc: "Khuddasikkhā-abhinavaṭīkā", tags: ["abhinavaṭīkā", "khuddasikkhā", "vinaya", "ṭīkā"], related_name: null, abbr: "khuddasikkhā.abhinavaṭī." },
  { id: 1926, book: 203, paragraph: 3100, title: "mūlasikkhā", sn: 249, toc: "Mūlasikkhā", tags: ["mūlasikkhā", "vinaya", "ṭīkā"], related_name: null, abbr: "mūlasikkhā." },
  { id: 1927, book: 203, paragraph: 3481, title: "mūlasikkhā", sn: 250, toc: "Mūlasikkhā-ṭīkā", tags: ["mūlasikkhā", "vinaya", "ṭīkā"], related_name: "vin11", abbr: "mūlasikkhā.ṭī." },
  { id: 1928, book: 204, paragraph: 3, title: "sāratthadīpanī-ṭīkā", sn: 251, toc: "Sāratthadīpanī-ṭīkā (paṭhamo bhāgo)", tags: ["dīpanī", "mahāvibhaṅga", "paṭhamo bhāgo", "pārājikapāḷi", "suttavibhaṅga", "sāratthadīpanī", "vinaya", "ṭīkā"], related_name: "vin1", abbr: "sārattha.ṭī.1." },
  { id: 1929, book: 205, paragraph: 3, title: "sāratthadīpanī-ṭīkā", sn: 252, toc: "(SAD) Pārājika-ṭīkā", tags: ["dutiyo bhāgo", "dīpanī", "mahāvibhaṅga", "pārājikapāḷi", "suttavibhaṅga", "sāratthadīpanī", "vinaya", "ṭīkā"], related_name: "vin1", abbr: "sārattha.ṭī.2." },
  { id: 1930, book: 206, paragraph: 3, title: "sāratthadīpanī-ṭīkā", sn: 253, toc: "(SAD) Pācittiya-ṭīkā", tags: ["dīpanī", "mahāvibhaṅga", "pācittiyapāḷi", "suttavibhaṅga", "sāratthadīpanī", "tatiyo bhāgo", "vinaya", "ṭīkā"], related_name: "vin2", abbr: "sārattha.ṭī.3." },
  { id: 1931, book: 206, paragraph: 717, title: "sāratthadīpanī-ṭīkā", sn: 254, toc: "(SAD) Mahāvagga-ṭīkā", tags: ["dīpanī", "khandhaka", "mahāvagga", "sāratthadīpanī", "vinaya", "ṭīkā"], related_name: "vin3", abbr: "sārattha.ṭī.3.mahāva." },
  { id: 1932, book: 206, paragraph: 1753, title: "sāratthadīpanī-ṭīkā", sn: 255, toc: "(SAD) Cūḷavagga-ṭīkā", tags: ["cūḷavagga", "dīpanī", "khandhaka", "sāratthadīpanī", "vinaya", "ṭīkā"], related_name: "vin4", abbr: "sārattha.ṭī.3.cūḷava." },
  { id: 1933, book: 206, paragraph: 2154, title: "sāratthadīpanī-ṭīkā", sn: 256, toc: "(SAD) Parivāra-ṭīkā", tags: ["dīpanī", "parivāra", "parivārapāḷi", "sāratthadīpanī", "vinaya", "ṭīkā"], related_name: "vin5", abbr: "sārattha.ṭī.3.pari." },
  { id: 1934, book: 207, paragraph: 3, title: "pātimokkhapāḷi", sn: 257, toc: "Bhikkhupātimokkhapāḷi", tags: ["bhikkhupātimokkha", "dvemātikāpāḷi", "pātimokkha", "pāḷi", "vinaya", "ṭīkā"], related_name: "vin6", abbr: "pātimokkha." },
  { id: 1935, book: 207, paragraph: 524, title: "pātimokkhapāḷi", sn: 258, toc: "Bhikkhunīpātimokkhapāḷi", tags: ["bhikkhunī", "bhikkhupātimokkha", "dvemātikāpāḷi", "pātimokkha", "pāḷi", "vinaya", "ṭīkā"], related_name: "vin6", abbr: "bhikkhunīpātimokkha." },
  { id: 1936, book: 207, paragraph: 1215, title: "kaṅkhāvitaraṇī", sn: 259, toc: "Kaṅkhāvitaraṇī-aṭṭhakathā", tags: ["dvemātikāpāḷi", "kaṅkhāvitaraṇī", "pātimokkha", "vinaya", "ṭīkā"], related_name: "vin6", abbr: "kaṅkhā.aṭṭha." },
  { id: 1937, book: 208, paragraph: 3, title: "vinayasaṅgaha-aṭṭhakathā", sn: 260, toc: "Vinayasaṅgaha-aṭṭhakathā", tags: ["vinaya", "vinayasaṅgaha", "ṭīkā"], related_name: "vin7", abbr: "vi.saṅga.aṭṭha." },
  { id: 1938, book: 209, paragraph: 3, title: "vajirabuddhi-ṭīkā", sn: 261, toc: "Vajirabuddhi-ṭīkā", tags: ["vajirabuddhi", "vinaya", "ṭīkā"], related_name: "vin1", abbr: "vajira.ṭī." },
  { id: 1939, book: 209, paragraph: 166, title: "vajirabuddhi-ṭīkā", sn: 262, toc: "Pārājikavaṇṇanā", tags: ["mahāvibhaṅga", "pārājika", "pārājikapāḷi", "suttavibhaṅga", "vajirabuddhi", "vinaya", "ṭīkā"], related_name: "vin1", abbr: "vajira.ṭī.pārā." },
  { id: 1940, book: 209, paragraph: 992, title: "vajirabuddhi-ṭīkā", sn: 263, toc: "Pācittiyavaṇṇanā", tags: ["pācittiya", "pācittiyapāḷi", "suttavibhaṅga", "vajirabuddhi", "vinaya", "ṭīkā"], related_name: "vin2", abbr: "vajira.ṭī.pāci." },
  { id: 1941, book: 209, paragraph: 1708, title: "vajirabuddhi-ṭīkā", sn: 264, toc: "Mahāvaggavaṇṇanā", tags: ["khandhaka", "mahāvagga", "vajirabuddhi", "vinaya", "ṭīkā"], related_name: null, abbr: "vajira.ṭī.mahāva." },
  { id: 1942, book: 209, paragraph: 2217, title: "vajirabuddhi-ṭīkā", sn: 265, toc: "Cūḷavaggavaṇṇanā", tags: ["cūḷavagga", "khandhaka", "vajirabuddhi", "vinaya", "ṭīkā"], related_name: "vin4", abbr: "vajira.ṭī.cūḷava." },
  { id: 1943, book: 209, paragraph: 2428, title: "vajirabuddhi-ṭīkā", sn: 266, toc: "Parivāravaṇṇanā", tags: ["parivāra", "parivārapāḷi", "vajirabuddhi", "vinaya", "ṭīkā"], related_name: "vin5", abbr: "vajira.ṭī.pari." },
  { id: 1944, book: 210, paragraph: 3, title: "vimativinodanī-ṭīkā", sn: 267, toc: "Bhikkhuvibhaṅgavaṇṇanā", tags: ["mahāvibhaṅga", "pārājikapāḷi", "suttavibhaṅga", "vimativinodanī", "vinaya", "ṭīkā"], related_name: "vin1", abbr: "vimati.ṭī." },
  { id: 1945, book: 210, paragraph: 1658, title: "vimativinodanī-ṭīkā", sn: 268, toc: "Bhikkhunīvibhaṅgavaṇṇanā", tags: ["bhikkhunī", "bhikkhunīvibhaṅga", "pācittiyapāḷi", "suttavibhaṅga", "vimativinodanī", "vinaya", "ṭīkā"], related_name: "vin2", abbr: "vimati.ṭī.bhikkhunī." },
  { id: 1946, book: 210, paragraph: 1779, title: "vimativinodanī-ṭīkā", sn: 269, toc: "Mahāvaggavaṇṇanā", tags: ["khandhaka", "mahāvagga", "vimativinodanī", "vinaya", "ṭīkā"], related_name: "vin3", abbr: "vimati.ṭī.mahāva." },
  { id: 1947, book: 210, paragraph: 2431, title: "vimativinodanī-ṭīkā", sn: 270, toc: "Cūḷavaggavaṇṇanā", tags: ["cūḷavagga", "khandhaka", "vimativinodanī", "vinaya", "ṭīkā"], related_name: "vin4", abbr: "vimati.ṭī.cūḷava." },
  { id: 1948, book: 210, paragraph: 2792, title: "vimativinodanī-ṭīkā", sn: 271, toc: "Parivāravaṇṇanā", tags: ["parivāra", "parivārapāḷi", "vimativinodanī", "vinaya", "ṭīkā"], related_name: "vin5", abbr: "vimati.ṭī.pari." },
  { id: 1949, book: 211, paragraph: 3, title: "vinayālaṅkāra-ṭīkā", sn: 272, toc: "Vinayālaṅkāra-ṭīkā", tags: ["vinaya", "vinayālaṅkāra", "ṭīkā"], related_name: "vin7", abbr: "vinayālaṅkāra.ṭī." },
  { id: 1950, book: 212, paragraph: 2, title: "kaṅkhāvitaraṇī", sn: 273, toc: "Kaṅkhāvitaraṇīpurāṇa-ṭīkā", tags: ["kaṅkhāvitaraṇī", "purāṇaṭīkā", "pātimokkha", "vinaya", "ṭīkā"], related_name: "vin6", abbr: "kaṅkhā.purāṇaṭī." },
  { id: 1951, book: 212, paragraph: 671, title: "kaṅkhāvitaraṇī", sn: 274, toc: "Kaṅkhāvitaraṇī-abhinavaṭīkā", tags: ["abhinavaṭīkā", "kaṅkhāvitaraṇī", "pātimokkha", "vinaya", "ṭīkā"], related_name: "vin6", abbr: "kaṅkhā.abhinavaṭī." },
  { id: 1952, book: 213, paragraph: 3, title: "vinayapitaka", sn: 275, toc: "(VN)Pārājikapāḷi", tags: ["mahāvibhaṅga", "mūla", "pārājika", "pārājikapāḷi", "pāḷi", "suttavibhaṅga", "vinaya"], related_name: "vin1", abbr: "pārā." },
  { id: 1953, book: 214, paragraph: 3, title: "vinayapitaka", sn: 276, toc: "(VN)Pācittiyapāḷi", tags: ["mahāvibhaṅga", "mūla", "pācittiyapāḷi", "pāḷi", "suttavibhaṅga", "vinaya"], related_name: "vin2", abbr: "pāci." },
  { id: 1954, book: 215, paragraph: 3, title: "vinayapitaka", sn: 277, toc: "(VN)Mahāvaggapāḷi", tags: ["khandhaka", "mahāvagga", "mūla", "pāḷi", "vinaya"], related_name: "vin3", abbr: "mahāva." },
  { id: 1955, book: 216, paragraph: 3, title: "vinayapitaka", sn: 278, toc: "(VN)Cūḷavaggapāḷi", tags: ["cūḷavagga", "khandhaka", "mūla", "pāḷi", "vinaya"], related_name: "vin4", abbr: "cūḷava." },
  { id: 1956, book: 217, paragraph: 3, title: "vinayapitaka", sn: 279, toc: "(VN)Parivārapāḷi", tags: ["mūla", "parivāra", "pāḷi", "vinaya"], related_name: "vin5", abbr: "pari." },
  { id: 1957, book: 139, paragraph: 925, title: "samantapāsādikā", sn: 280, toc: "Bhikkhunīvibhaṅgavaṇṇanā", tags: ["aṭṭhakathā", "bhikkhunī", "bhikkhunīvibhaṅga", "pācittiya", "pācittiya-aṭṭhakathā", "samantapāsādikā", "suttavibhaṅga", "vinaya"], related_name: "vin2", abbr: "pāci.aṭṭha.bhikkhunī." },
  { id: 1958, book: 214, paragraph: 2162, title: "(VN)Bhikkhunīvibhaṅgo", sn: 281, toc: "(VN)Bhikkhunīvibhaṅgo", tags: ["bhikkhunī", "bhikkhunīvibhaṅga", "mūla", "pācittiyapāḷi", "pāḷi", "suttavibhaṅga", "vinaya"], related_name: "vin2", abbr: "pāci.bhikkhunī." },
];

const BY_KEY = new Map<string, BookRow>(
  BOOK_ROWS.map((r) => [`${r.book}-${r.paragraph}`, r]),
);

/** 按 (book, paragraph) 精确查书；查不到时回退到同 book 内 paragraph 最大且不超过目标的行。 */
export function lookupBook(book: number, paragraph: number): BookRow | undefined {
  const exact = BY_KEY.get(`${book}-${paragraph}`);
  if (exact) return exact;
  let best: BookRow | undefined;
  for (const r of BOOK_ROWS) {
    if (r.book === book && r.paragraph <= paragraph) {
      if (!best || r.paragraph > best.paragraph) best = r;
    }
  }
  return best;
}

/** 在 path 里找第一个能精确匹配书表的节点（实证上 path[0] 是 level-0 丛书根，书级节点是 path[1]）。 */
export function lookupBookByPath(path: unknown, fallbackBook?: number, fallbackParagraph?: number): BookRow | undefined {
  if (Array.isArray(path)) {
    for (const item of path) {
      if (typeof item !== "object" || item === null) continue;
      const b = Number((item as Record<string, unknown>).book);
      const p = Number((item as Record<string, unknown>).paragraph);
      if (!Number.isFinite(b) || !Number.isFinite(p)) continue;
      const hit = BY_KEY.get(`${b}-${p}`);
      if (hit) return hit;
    }
  }
  if (fallbackBook != null && fallbackParagraph != null) return lookupBook(fallbackBook, fallbackParagraph);
  return undefined;
}

